### ISSUE TITLE
the method  GetVoxelSize

### ISSUE THREAD

**Issue by ronangithub** [kaminaritukane/SVON#1]
Hello,
the file 'SVONVolume.cpp'    , it's method  'GetVoxelSize'  (line 59)   , 

temp leastVoxelSize =  extent.x / 2^power .    is  the first layer 's voxel size, 
the size  = leastVoxelSize * 2 ^ (aLayer+1)  ??   mabey is （aLayer）? why need +1?

like the wiki examples， 
power =2 , extent.x = 4..
temp leastVoxelSize = 4/2*2 = 1.
0  layer , return 1 * 2^0 = 1 ?  or  return 1*2^(0+1) = 2 ??
and 1 layer, return 1 * 2^1 = 2 ? or return 1*2 ^ 2 = 4 ??
and 2 layer ,4 or 8?

like the +1 is redundant？

looking forward to the author's reply

**Comment by kaminaritukane** [comment]
Take VoxelPower = 2, Extent = 1 for example:

![image](https://user-images.githubusercontent.com/3223585/138630180-8952c9d3-b389-4c4b-aa2c-e9184d54bcf8.png)

**Comment by kaminaritukane** [comment]
Another example with VoxelPower = 3, Extent = 1

![image](https://user-images.githubusercontent.com/3223585/138283723-26902464-25de-4508-86b4-ed24993dfcf6.png)
![image](https://user-images.githubusercontent.com/3223585/138283745-d92c9da0-ccec-4cf4-9d16-ee5702aa9a4c.png)
![image](https://user-images.githubusercontent.com/3223585/138283773-315215e4-2f65-4afa-99ea-526aa433aa6b.png)
![image](https://user-images.githubusercontent.com/3223585/138283805-592329c5-e5ae-4d1d-b45d-37a319761bba.png)

**Comment by ronangithub** [comment]
yep，i got it..
i have a wrong with "extent".  the  extent is   the distance between center to the border  。
thank u!
